version: '3'

services:
  consumer:
    build: consumer-service-using-python
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
  publisher:
    build: publication-service-java
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
  db:
    image: postgres